#!/usr/bin/env python
# Copyright 2010 Torbjorn Bjorkman
# This file is part of cif2cell
#
# cif2cell is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cif2cell is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cif2cell.  If not, see <http://www.gnu.org/licenses/>.
#
#************************************************************************************
#  Description: A command-line tool to generate the geometrical setup
#               for various electronic structure codes from a CIF format file.
#               This code was published in Comp. Phys, Comm. 182, 1183-1186 (2011).
#  Author:      Torbjorn Bjorkman, torbjorn.bjorkman(at)aalto.fi
#  Affiliation: COMP, Aaalto University School of Science,
#               Department of Applied Physics, Espoo, Finland
#************************************************************************************
from __future__ import division
import os
import sys
import string
from math import *
from datetime import datetime
from optparse import OptionParser, OptionGroup
import warnings
import CifFile
import subprocess
from utils import *
from uctools import *
from ESPInterfaces import *
from elementdata import *

# Name and version
programname = "cif2cell"
version = "0.4.5"

# Turn of warnings about deprecated stuff
warnings.simplefilter("ignore",DeprecationWarning)

############################
#      INPUT OPTIONS       #
############################
# General stuff
description = "A program for generating input lattice structures to various electronic structure programs from a CIF (Crystallographic Information Framework) file. This code was published in "
usage = "usage: %prog FILE [-p PROGRAM] [other options]"
parser = OptionParser(usage=usage, description=description)
parser.add_option("-v","--verbose",dest="verbose",help="Print a lot of extra information to screen",action="store_true")
parser.add_option("--version",dest="version",help="Print version number.",action="store_true")
parser.add_option("-q","--quiet",dest="quiet",help="Suppress most screen output, such as warnings and overrides --verbose flag, but will print all other requested output.",action="store_true")
parser.add_option("-f","--file",dest="file",help="Input CIF file, unless given as first argument to the program.",metavar="FILE")
parser.add_option("-p","--program",dest="program",help="The electronic structure code you want to create input file(s) for. Currently supports: abinit, castep, cpmd, cellgen, crystal09, elk, emto, exciting, fleur, ncol, rspt, siesta, spacegroup, sprkkr, vasp, xband. This keyword is case insensitive.")
parser.add_option("-o","--outputfile",dest="outputfile",help="Name of output file (if other than default for you electronic structure code).",metavar="FILE")
parser.add_option("-a","--append",dest="append",help="Append the output to given output file rather than overwriting.",action="store_true")
parser.add_option("--grammar",dest="grammar",help="Set the CIF grammar to be used when parsing the input file (default is 1.1).")
parser.add_option("--which-filename",dest="filenamequery",help="If given together with the --program-name option, the name of the output file will be printed to screen.",action="store_true")
parser.add_option("-b","--block",dest="block",help="Block of data in input file (if there are more than one block in the CIF file).")
parser.add_option("--force-alloy",dest="forcealloy",help="Force generation of output file for an alloy compound for an electronic structure code that does not implement any alloy theory (such as CPA).",action="store_true")
parser.add_option("--coordinate-tolerance",dest="coordtol",help="Parameter for determining when two coordinates are the same (default=0.0002).")
parser.add_option("--setup-all",dest="setupall",help="Make a complete setup, not just the geometrical part. This is currently only available for VASP.",action="store_true")
parser.add_option("--k-resolution",dest="kresolution",help="The desired resolution in k-space (default=0.2). Used for generating k-space grid options if --setup-all is specified.")
# OUTPUT OPTIONS
parser.add_option("--print-digits",dest="printdigits",help="Number of digits used when printing coordinates etc. to screen (default=8). Useful if you need to tweak the screen output for cutting and pasting into some unsupported program. There is no point in going over 16 because of the floating point accuracy.")
parser.add_option("--print-atomic-units",dest="printau",help="Output lattice parameters in bohrradii rather than angstrom.",action="store_true")
parser.add_option("--print-cartesian",dest="printcart",help="Atomic sites printed to screen in cartesian rather than lattice coordinates.",action="store_true")
parser.add_option("--print-symmetry-operations",dest="printsymops",help="Print symmetry operations of the generated cell.",action="store_true")
parser.add_option("--print-seitz-matrices",dest="printseitz",help="Print symmetry operations of the generated cell in Seitz matrix form.",action="store_true")
parser.add_option("--print-charge-state","--print-oxidation-numbers",dest="printcharges",help="Print information about the oxidation state from the CIF file.",action="store_true")
parser.add_option("--print-reference-bibtex",dest="bibtexref",help="Print citation in BibTeX format and exit.",action="store_true")
# CELL GENERATION OPTIONS
#cellgenopts = OptionGroup(parser, "Cell generation options")
#parser.add_option("--rhombohedral-diagonal",dest="rhombdiag",help="Set up rhombohedral cell with threefold axis along [111].",action="store_true")
parser.add_option("--no-reduce",dest="noreduce",help="Do not reduce to the primitive cell.",action="store_true")
# Supercell options
parser.add_option("--supercell",dest="supercellmap",help="Three integers separated with commas and enclosed in square brackets that specify the dimensions of a supercell to be constructed from the primitive cell. If combined with the --no-reduce option the supercell will instead be generated based on the conventional cell.",metavar="[k,l,m]")
parser.add_option("--supercell-vacuum",dest="supercellvacuum",help="Three numbers >=0 separated with commas and enclosed in square brackets that specify a number of unit cell units of vacuum to be added along the first, second or third of the generated lattice vectors.",metavar="[k,l,m]")
parser.add_option("--supercell-translation-vector",dest="supercelltransvec",help="Three numbers separated with commas and enclosed in square brackets that specify a final shift of all atomic positions in the final cell (in units of the lattice vectors of the new cell).",metavar="[k,l,m]")
parser.add_option("--supercell-sort",dest="supercellsort",help="Sort the atom positions by some scheme. Currently available are:     1) By cartesian coordinate - example: xzy will sort first on x then on z then on y.     2) by lattice vector - example: 132 will sort first by lattice vector 1 then by lattice vector 3 and last by lattice vector 2.")
# PROGRAM SPECIFIC OPTIONS
progspec = OptionGroup(parser, "Program specific options")
# emto
progspec.add_option("--emto-hard-sphere-radii",dest="hardsphereradii",help="Set hard spheres in KSTR to something other than the default (=0.67).")
# RSPt
progspec.add_option("--rspt-new", dest="newsymt", help="Generate a symt.inp file in the new format.", action="store_true")
progspec.add_option("--rspt-spinpol", dest="rsptspinpol", help="Generate new format symt.inp file with spin polarization.", action="store_true")
progspec.add_option("--rspt-relativistic", dest="rsptrelativistic", help="Generate new format symt.inp file with relativistic effects.", action="store_true")
progspec.add_option("--rspt-spinaxis", dest="rsptspinaxis", help="Spin axis for symt.inp (default is [0.0,0.0,0.0].", metavar="[x,y,z]")
progspec.add_option("--rspt-mtradii", dest="rsptmtradii", help="Integer that gives the method for setting muffin tin radii.", metavar="N")
# cellgen
progspec.add_option("--cellgen-map",dest="cellgenmap",help="Nine integers separated with commas and enclosed three and three in square brackets (this is a matrix in Python) that specify the map to a supercell to be output for the RSPt supercell generator 'cellgen'. Overrides --cellgen-supercell-dims.",metavar="[[k,l,m],[n,o,p],[q,r,s]]")
progspec.add_option("--cellgen-supercell-dimensions",dest="cellgensupercelldims",help="Three integers separated with commas and enclosed in square brackets that specify the dimensions of a supercell to be output to the RSPt supercell generator 'cellgen' (the diagonal elements of the 'map').",metavar="[k,l,m]")
progspec.add_option("--cellgen-reference-vector",dest="cellgenrefvec",help="Three reals separated with commas and enclosed in square brackets that specify an optional shift of the origin used by the RSPt supercell generator 'cellgen'.",metavar="[x,y,z]")
# CPMD
progspec.add_option("--cpmd-cutoff",dest="cpmdcutoff",help="Set the cutoff written to the &SYSTEM block (default=100.0 Ry).")
# SPRKKR/xband
progspec.add_option("--sprkkr-minangmom",dest="sprkkrminangmom",help="Enforce minimum onsite angular momentum (=l+1, so that 3 will be d-states).")
# spacegroup
progspec.add_option("--spacegroup-supercell",dest="spacegroupsupercell",help="Three integers separated with commas and enclosed in square brackets that specify the dimensions of a supercell to be output to the elk input generator 'spacegroup'.",metavar="[k,l,m]")
# VASP
progspec.add_option("--vasp-format",dest="vaspformat",help="Format of the generated POSCAR file, either 4 or 5. Default is 4.")
progspec.add_option("--vasp-print-species",dest="vaspprintspcs",help="Print the atomic species to screen in the order they are put in the POSCAR file (useful for scripting).",action="store_true")
progspec.add_option("--vasp-cartesian",dest="vaspcart",help="Write lattice vectors and positions to POSCAR file in cartesian coordinates and set length to 1.",action="store_true")
progspec.add_option("--vasp-cartesian-lattice-vectors",dest="vaspcartvecs",help="Write lattice vectors to POSCAR file in cartesian coordinates and set the length scale to 1.",action="store_true")
progspec.add_option("--vasp-cartesian-positions",dest="vaspcartpos",help="Write atomic positions to POSCAR file in Cartesian rather than Direct coordinates.",action="store_true")
progspec.add_option("--vasp-pseudo-libdr",dest="vasppseudolib",help="Path to the VASP pseudopotential library.")
parser.add_option_group(progspec)
(options,args) = parser.parse_args()

# Print version number and exit
if options.version:
    print programname+" version "+version
    sys.exit(0)

# Electronic structure program
if options.program:
    outputprogram = options.program.lower()
else:
    outputprogram = None

# recast some input parameters
if options.noreduce or outputprogram == "cif":
    reducetoprim = False
else:
    reducetoprim = True

# Set verbosity level
if options.verbose and not options.quiet:
    verbose = True
else:
    verbose = False

# Various parameters
# Output reference in specific format?
if options.bibtexref:
    bibtexref = True
else:
    bibtexref = False
# Programs that can deal with alloys
alloyprograms = set(["emto","kstr","bmdl","shape","kgrn","kfcd","cif","sprkkr","xband"])
# Initialize element data
ed = ElementData()
# Number of positions for printing decimal numbers to screen
if type(options.printdigits) == type(None):
    decpos = 8 + 3
else:
    decpos = int(options.printdigits) + 3
# format string for outputting decimal numbers to screen
decform = "%"+str(decpos)+"."+str(decpos-4)+"f"
threedecs = " "+decform+" "+decform+" "+decform
fourdecs = " "+decform+" "+decform+" "+decform+" "+decform
# For printing time
today = datetime.today()
datestring = str(today.year)+"-"+str(today.month).rjust(2,'0')+"-"+str(today.day).rjust(2,'0')+' '+str(today.hour)+":"+str(today.minute).rjust(2,'0')

# Printing of symmetry operations
if options.printsymops:
    printsymops = True
else:
    printsymops = False
if options.printseitz:
    printseitz = True
else:
    printseitz = False

if options.printcharges:
    printcharges = True
else:
    printcharges = False

# complete setup options
if options.setupall:
    setupall = True
else:
    setupall = False
# k-space resolution
if options.kresolution:
    kresolution=float(options.kresolution)
else:
    kresolution=0.2

# Open and read CIF file
cif_file = None
if len(sys.argv) > 1:
    # input CIF file as argument
    cif_file = sys.argv[1]
if options.file:
    # input CIF file as option (overrides argument)
    cif_file = options.file
if cif_file:
    if not os.path.exists(cif_file):
        sys.stderr.write("***Error: The file "+cif_file+" could not be found.\n")
        sys.exit(2)
    cif_file_name = cif_file.split("/")[-1]
    # Set CIF grammar
    if options.grammar:
        cif_grammar = options.grammar
    else:
        cif_grammar = '1.1'
    # Skip validation for now... it causes too much trouble.
    ## cdic = CifFile.CifDic("cif_core.dic",grammar='1.1')     
    ## val_results = CifFile.validate(cif_file,dic=cdic)
    ## print validate_report(val_results)
    ## val_report = CifFile.ValidationResult(val_results)
    try:
        cf = CifFile.ReadCif(cif_file,grammar=cif_grammar)
    except:
        sys.stderr.write("***Error: could not read "+cif_file+".\n")
        sys.exit(2)
else:
    sys.stderr.write("***Error: No input CIF file given\n")
    sys.exit(2)

# Make supercell?
if options.supercellmap or options.supercellvacuum or options.supercelltransvec:
    makesupercell = True
    if options.supercellmap:
        supercellmap = eval(options.supercellmap)
    else:
        supercellmap = [1,1,1]
    if options.supercellvacuum:
        supercellvacuum = eval(options.supercellvacuum)
    else:
        supercellvacuum = [0,0,0]
    if options.supercelltransvec:
        supercelltransvec = eval(options.supercelltransvec)
    else:
        supercelltransvec = [0,0,0]
    # 
    if options.supercellsort:
        supercellsort = options.supercellsort.lower()
    else:
        supercellsort = ""
else:
    makesupercell = False

##############################################
# Get blocks
cfkeys = cf.keys()
if options.block:
    cb = cf.get(options.block)
    if type(cb) == type(None):
        sys.stderr.write("***Error: No block "+options.block+" in "+cif_file+".\n")
        sys.exit(2)
else:
    cb = cf.get(cfkeys[0])
# Get reference data
ref = ReferenceData()
ref.getFromCIF(cb)
if bibtexref:
    print ref.bibtexref()
    sys.exit(0)
# Get cell data
cd = CellData()
# suppress warnings if requested
cd.quiet = options.quiet
if options.coordtol:
    cd.coordepsilon = float(options.coordtol)
try:
    cd.getFromCIF(cb)
except PositionError, e:
    sys.stderr.write("***Error: cell setup: "+e.value+"\n")
    sys.exit(2)
except CellError, e:
    sys.stderr.write("***Error: cell setup: "+e.value+"\n")
    sys.exit(2)
except SymmetryError, e:
    sys.stderr.write("***Error: cell setup: "+e.value+"\n")
    sys.exit(2)


##############################################
# Generate cell
if reducetoprim:
    ## if options.rhombdiag:
    ##     cd.rhombohedral_diagonal = True
    try:
        cell = cd.primitive()
    except SymmetryError, e:
        sys.stderr.write("***Error: cell setup: "+e.value+"\n")
        sys.exit(2)
else:
    try:
        cell = cd.conventional()
    except SymmetryError, e:
        sys.stderr.write("***Error: cell setup: "+e.value+"\n")
        sys.exit(2)


# Print cell
if verbose or not options.program and not options.quiet:
    print string.upper(programname)+" "+version
    print datestring
    # Print compound
    compoundstring = "Output for "
    if ref.cpd == "" and ref.compound == "":
        compoundstring += "unknown compound"
    if ref.cpd != "":
        compoundstring += ref.cpd
    if ref.compound != "":
        compoundstring += " ("+ref.compound+")"
    print compoundstring
    # Print database
    print ref.databasestring
    if cell.alloy and options.forcealloy and options.program:
        print "\nEnforcing generation of file(s) for "+outputprogram+" for an alloy."
    print "\n BIBLIOGRAPHIC INFORMATION"
    refstrings = ref.referencestring().split()
    tmpstring = ""
    i = 0
    while i < len(refstrings):
        if len(tmpstring+refstrings[i]+" ") < 70:
            tmpstring += refstrings[i]+" "
            i += 1
        else:
            print tmpstring
            tmpstring = ""
    if tmpstring != "":
        print tmpstring
    print "\n SYMMETRY INFORMATION"
    if cd.HallSymbol != "":
        print cd.crystal_system()[0].upper()+cd.crystal_system()[1:]+" crystal system."
        print "Space group number     : ".rjust(2)+str(cd.spacegroupnr)
        print "Hall symbol            : "+cd.HallSymbol
        print "Hermann-Mauguin symbol : "+cd.HMSymbol
    else:
        print "No space group information found."
    # only print these if verbose
    if verbose:
        print "Symmetry equivalent sites:"
        for i in range(len(cd.symops)):
            print "%4i  %8s, %8s, %8s" % (i+1, cd.symops[i].eqsite[0], cd.symops[i].eqsite[1], cd.symops[i].eqsite[2])
    if printsymops or printseitz or verbose:
        # Print symmetry operations. Need to make list of it to control order.
        symoplist = sorted(list(cell.symops))
        if printsymops or verbose:
            print "\nSymmetry operations : "
            print "  3x3 rotation matrix +"
            print "  3x1 translation vector"
            i = 1
            for op in symoplist:
                print "Operation "+str(i)
                for v in op.rotation:
                    print threedecs%(v[0],v[1],v[2])
                print threedecs%(op.translation[0],op.translation[1],op.translation[2])
                i += 1
        if printseitz:
            print "\nSymmetry operations :"
            print "  In Seitz matrix form"
            i = 1
            for op in symoplist:
                print "Operation "+str(i)
                tmpstring = ""
                for j in range(3):
                    tmpstring += fourdecs%(op.rotation[j][0],op.rotation[j][1],op.rotation[j][2],op.translation[j])+"\n"
                tmpstring += fourdecs%(0,0,0,1)
                print tmpstring
                i += 1    
    print "\n INPUT CELL INFORMATION"
    print "Lattice parameters:"
    tmpstring = ""
    for i in ["a", "b", "c"]:
        tmpstring += i.rjust(decpos)+" "
    print tmpstring
    formatstring = ""
    if options.printau:
        ## aprint = cd.ainit*angtobohr
        ## bprint = cd.binit*angtobohr
        ## cprint = cd.cinit*angtobohr
        aprint = cd.a*angtobohr
        bprint = cd.b*angtobohr
        cprint = cd.c*angtobohr
    else:
        ## aprint = cd.ainit
        ## bprint = cd.binit
        ## cprint = cd.cinit
        aprint = cd.a
        bprint = cd.b
        cprint = cd.c
    for i in range(3):
        formatstring = formatstring+decform+" "
    print formatstring % (aprint, bprint, cprint)
    tmpstring = ""
    for i in ["alpha", "beta", "gamma"]:
        tmpstring += i.rjust(decpos)+" "
    print tmpstring
    print formatstring % (cd.alpha, cd.beta, cd.gamma)
    ## print formatstring % (cd.alphainit, cd.betainit, cd.gammainit)
    # Pretty printing in columns that need to have variable width
    # w1 = width of the atomic species column
    # w2 = width of a decimal column
    # w3 = width of the occupancy column
    # w4 = width of the charge state column
    if cell.alloy:
        w1 = 0
        w3 = 0
        w4 = 0
        # Find atom and occupation column widths
        for a in cell.atomdata:
            for b in a:
                tmpstring1 = ""
                tmpstring2 = ""
                tmpstring3 = ""
                for k,v in b.species.iteritems():
                    tmpstring1 += k+"/"
                    tmpstring2 += str(v).rstrip("0.")+"/"
                    # charge output
                    for k2,v2 in cell.chargedict.iteritems():
                        if k2.strip(string.punctuation+string.digits) == k:
                            tmpstring3 += str(v2)+"/"
                tmpstring1 = tmpstring1.rstrip("/")
                tmpstring2 = tmpstring2.rstrip("/")
                tmpstring3 = tmpstring3.rstrip("/")
                w1 = max(w1,len(tmpstring1))
                w3 = max(w3,len(tmpstring2))
                w4 = max(w4,len(tmpstring3))
        # small aesthetic adjustment 
        w1 = w1 + 1
        w3 = w3 + 2
        w4 = max(w4 + 2, 8)
    else:
        w1 = 5
        w2 = decpos
        w3 = 0
        # width of charge column
        if printcharges:
            w4 = 7
        else:
            w4 = 0
    # Now for the output...
    tmpstring = "Representative sites :"
    print tmpstring
    siteheader = "Atom".ljust(w1)+" "
    if options.printcart:
        transmtx = []
        for i in range(3):
            transmtx.append([])
            for j in range(3):
                transmtx[i].append(cell.latticevectors[i][j]*cd.a)
            i += 1
        for i in ["x","y","z"]:
            siteheader += i.rjust(decpos)+" "
    else:
        transmtx = [[1, 0, 0],
                    [0, 1, 0],
                    [0, 0, 1]]
        for i in ["a1","a2","a3"]:
            siteheader += i.rjust(decpos)+" "
    if cell.alloy:
        if w3 > 13:
            siteheader += "occupancies".rjust(w3)
        else:
            siteheader += "occ.".rjust(w3)
    if printcharges:
        siteheader += " "+"charge".rjust(w4)
    print siteheader
    # Representative sites
    for i in range(len(cell.ineqsites)):
        tmpstring = ""
        occstring = ""
        chargestring = ""
        for k,v in cell.occupations[i].iteritems():
            tmpstring += k+"/"
            occstring += str(v)+"/"
            # charge output
            for k2,v2 in cell.chargedict.iteritems():
                if k2.strip(string.punctuation+string.digits) == k:
                    chargestring += str(v2)+"/"
        tmpstring = tmpstring.rstrip("/")
        occstring = occstring.rstrip("/")
        chargestring = chargestring.rstrip("/")
        v = [t for t in cell.ineqsites[i]]
        tmpstring = tmpstring.ljust(w1) + threedecs % (v[0],v[1],v[2])
        if cell.alloy:
            tmpstring += " "+occstring.rjust(w3)
        if printcharges:
            tmpstring += " "+chargestring.rjust(w4)
        print tmpstring
    print "\n OUTPUT CELL INFORMATION"
    tmpstring = "Bravais lattice vectors :"
    if options.printcart:
        fact = cd.a
    else:
        fact = 1
    print tmpstring
    formatstring = ""
    for i in range(3):
        formatstring = formatstring+decform+" "
    for i in range(3):
        print formatstring % (cell.latticevectors[i][0]*fact, cell.latticevectors[i][1]*fact, cell.latticevectors[i][2]*fact)
    # Print out all sites
    tmpstring = "All sites, "
    if options.printcart:
        tmpstring += "(cartesian coordinates):"
    else:
        tmpstring += "(lattice coordinates):"
    print tmpstring
    print siteheader
    for a in cell.atomdata:
        for b in a:
            spcsstring = ""
            occstring = ""
            chargestring = ""
            for k,v in b.species.iteritems():
                spcsstring += k+"/"
                occstring += str(v).rstrip("0.")+"/"
                # charge output
                for k2,v2 in cell.chargedict.iteritems():
                    if k2.strip(string.punctuation+string.digits) == k:
                        chargestring += str(v2)+"/"
            spcsstring = spcsstring.rstrip("/")
            occstring = occstring.rstrip("/")
            chargestring = chargestring.rstrip("/")
            v = mvmult3(transmtx,b.position)
            tmpstring = spcsstring.ljust(w1)+threedecs%(v[0],v[1],v[2])
            if cell.alloy:
                tmpstring += " "+occstring.rjust(w3)
            if printcharges:
                tmpstring += " "+chargestring.rjust(w4)
            print tmpstring

##############################################
# Generate supercell
if makesupercell:
    try:
        supercell = cd.getSuperCell(supercellmap,supercellvacuum,supercelltransvec,sort=supercellsort)
    except CellError, e:
        sys.stderr.write("***Error: Supercell setup: "+e.value+"\n")
        sys.exit(2)
    # Print supercell
    if verbose or not options.program and not options.quiet:
        print "\n SUPERCELL INFORMATION"
        tmpstring = "Bravais lattice vectors :"
        if options.printcart:
            fact = cd.a
        else:
            fact = 1
        print tmpstring
        formatstring = ""
        for i in range(3):
            formatstring = formatstring+decform+" "
        for i in range(3):
            print formatstring % (supercell.latticevectors[i][0]*fact, supercell.latticevectors[i][1]*fact, supercell.latticevectors[i][2]*fact)
        # Print out all sites
        tmpstring = "All sites, "
        if options.printcart:
            tmpstring += "(cartesian coordinates):"
            transmtx = []
            for i in range(3):
                transmtx.append([])
                for j in range(3):
                    transmtx[i].append(cell.latticevectors[i][j]*cd.a)
                i += 1
        else:
            tmpstring += "(lattice coordinates):"
            transmtx = [[1, 0, 0],
                        [0, 1, 0],
                        [0, 0, 1]]
        print tmpstring
        print siteheader
        for a in cell.atomdata:
            for b in a:
                spcsstring = ""
                occstring = ""
                for k,v in b.species.iteritems():
                    spcsstring += k+"/"
                    occstring += str(v).rstrip("0.")+"/"
                spcsstring = spcsstring.rstrip("/")
                occstring = occstring.rstrip("/")
                v = mvmult3(transmtx,b.position)
                tmpstring = spcsstring.ljust(w1)+threedecs%(v[0],v[1],v[2])
                if cell.alloy:
                    tmpstring += " "+occstring.rjust(w3)
                print tmpstring
    if printsymops or printseitz or verbose:
        # Print symmetry operations. Need to make list of it to control order.
        symoplist = sorted(list(cell.symops))
        if printsymops or verbose:
            print "\nSymmetry operations : "
            print "  3x3 rotation matrix +"
            print "  3x1 translation vector"
            i = 1
            for op in symoplist:
                print "Operation "+str(i)
                for v in op.rotation:
                    print threedecs%(v[0],v[1],v[2])
                print threedecs%(op.translation[0],op.translation[1],op.translation[2])
                i += 1
        if printseitz:
            print "\nSymmetry operations :"
            print "  In Seitz matrix form"
            i = 1
            for op in symoplist:
                print "Operation "+str(i)
                tmpstring = ""
                for j in range(3):
                    tmpstring += fourdecs%(op.rotation[j][0],op.rotation[j][1],op.rotation[j][2],op.translation[j])+"\n"
                tmpstring += fourdecs%(0,0,0,1)
                print tmpstring
                i += 1    
                
    # update cell to the supercell
    cell = supercell

##############################################
# Sort sites so that the ones occupied by the heaviest elements come first,
# if the Python version supports this form of the max function and there is
# nothing wrong with the site data.
try:
    cell.atomdata.sort(key = lambda a: ed.elementnr[max(a[0].species, key = a[0].species.get)], reverse=True)
except:
    pass

##############################################
# Output file mode (overwrite or append?)
if options.append:
    outmode = "a"
else:
    outmode = "w"
# Output file. ot parsed until this point, since the default file names for some of
# the codes contain the names of space group and compound.
if options.outputfile:
    outputfile = options.outputfile
else:
    # Default output filenames for different programs
    if outputprogram == "vasp":
        outputfile = "POSCAR"
    elif outputprogram == "rspt":
        outputfile = "symt.inp"
    elif outputprogram == "cellgen":
        outputfile = "cellgen.inp"
    elif outputprogram == "elk":
        outputfile = "GEOMETRY.OUT"
    elif outputprogram == "exciting":
        outputfile = "input.xml"
    elif outputprogram == "spacegroup":
        outputfile = "spacegroup.in"
    elif outputprogram == "abinit":
        outputfile = ref.cpd.replace(" ", "").replace("(","").replace(")","")
        # If the filename seems too long or strange, replace by the name of the cif file
        if len(outputfile.strip(string.punctuation)) == 0:
            outputfile = cif_file_name.replace(".cif","")
        if len(outputfile) > 24:
            if len(cif_file_name) < len(outputfile):
                outputfile = cif_file_name.replace(".cif","")
            else:
                outputfile = outputfile[0:9]
        outputfile = outputfile+".in"
    elif outputprogram == "siesta":
        outputfile = ref.cpd.replace(" ", "").replace("(","").replace(")","")
        # If the filename seems too long or strange, replace by the name of the cif file
        if len(outputfile.strip(string.punctuation)) == 0:
            outputfile = cif_file_name.replace(".cif","")
        if len(outputfile) > 24:
            if len(cif_file_name) < len(outputfile):
                outputfile = cif_file_name.replace(".cif","")
            else:
                outputfile = outputfile[0:9]
        outputfile = outputfile+".fdf"
    elif outputprogram == "cpmd":
        outputfile = ref.cpd.replace(" ", "").replace("(","").replace(")","")
        # If the filename seems too long or strange, replace by the name of the cif file
        if len(outputfile.strip(string.punctuation)) == 0:
            outputfile = cif_file_name.replace(".cif","")
        if len(outputfile) > 24:
            if len(cif_file_name) < len(outputfile):
                outputfile = cif_file_name.replace(".cif","")
            else:
                outputfile = outputfile[0:9]
        outputfile = outputfile+".inp"
    elif outputprogram == "castep":
        outputfile = ref.cpd.replace(" ", "").replace("(","").replace(")","")
        # If the filename seems too long or strange, replace by the name of the cif file
        if len(outputfile.strip(string.punctuation)) == 0:
            outputfile = cif_file_name.replace(".cif","")
        if len(outputfile) > 24:
            if len(cif_file_name) < len(outputfile):
                outputfile = cif_file_name.replace(".cif","")
            else:
                outputfile = outputfile[0:9]
        outputfile = outputfile+".cell"
    elif outputprogram == "fleur":
        outputfile = ref.cpd.replace(" ", "").replace("(","").replace(")","")
        # If the filename seems too long or strange, replace by the name of the cif file
        if len(outputfile.strip(string.punctuation)) == 0:
            outputfile = cif_file_name.replace(".cif","")
        if len(outputfile) > 24:
            if len(cif_file_name) < len(outputfile):
                outputfile = cif_file_name.replace(".cif","")
            else:
                outputfile = outputfile[0:9]
        outputfile = "inp_"+outputfile
    elif outputprogram == "crystal09":
        outputfile = ref.cpd.replace(" ", "").replace("(","").replace(")","")
        # If the filename seems too long or strange, replace by the name of the cif file
        if len(outputfile.strip(string.punctuation)) == 0:
            outputfile = cif_file_name.replace(".cif","")
        if len(outputfile) > 24:
            if len(cif_file_name) < len(outputfile):
                outputfile = cif_file_name.replace(".cif","")
            else:
                outputfile = outputfile[0:9]
        # This is the naming convention from a large bunch of test cases, no idea why
        outputfile = outputfile+".d12"
    elif outputprogram == "sprkkr" or outputprogram == "xband":
        outputfile = ref.cpd.replace(" ", "").replace("(","").replace(")","")
        # If the filename seems too long or strange, replace by the name of the cif file
        if len(outputfile.strip(string.punctuation)) == 0:
            outputfile = cif_file_name.replace(".cif","")
        if len(outputfile) > 24:
            if len(cif_file_name) < len(outputfile):
                outputfile = cif_file_name.replace(".cif","")
            else:
                outputfile = outputfile[0:9]
        outputfile = outputfile+".sys"
    elif outputprogram == "cif":
        outputfile = cif_file_name.replace(".cif","")+"_allatoms.cif"
    else:
        outputfile = ""

# Print output filename to screen
if outputprogram !="":
    if (verbose or options.filenamequery) and outputfile != "":
        print "Data will be written to the file "+outputfile

################################################################################################
# stuff that should be printed irrespective of the verbose flag
if cell.alloy and options.forcealloy and options.program and not verbose:
    tmpstring = "Enforcing file generation for alloy. "
    if outputprogram == 'bstr' or outputprogram == 'vasp' or outputprogram == 'cpmd':
        print tmpstring
    else:
        tmpstring += "Warning! The file(s) will be incomplete!"
        print tmpstring
    
################################################################################################
# Stop here if no specific output was requested
if not options.program:
    sys.exit(0)

# Don't generate output for alloys (for most programs)
if cell.alloy and not options.forcealloy and not outputprogram in alloyprograms:
    print "Error: This system is an alloy, but the electronic structure code "+outputprogram+" has no way of dealing with alloys.\nRun again with --force-alloy if you want to generate an (incomplete) output file anyway."
    sys.exit(17)

# Function for printing a standard docstring
def StandardDocstring():
    stringlen = max(len(ref.referencestring()),len(ref.cpd+"   ("+ref.compound+")"))
    docstring = ""
    tmpstring = ""
    tmpstring = tmpstring.ljust(stringlen+4,'*')+'\n'
    docstring += tmpstring
    tmpstring2 = 'Generated by '+programname+' '+version+' '+datestring
    tmpstring2 = '* '+tmpstring2.center(stringlen)+' *\n'
    docstring += tmpstring2
    if ref.database != "":
        tmpstring2 = 'Data obtained from '+ref.databaseabbr[ref.database]
        if ref.databasecode != "":
            tmpstring2 += ". Reference number : "+ref.databasecode
        tmpstring2 = '* '+tmpstring2.center(stringlen)+' *\n'
        docstring += tmpstring2
    tmpstring2 = ref.cpd+"   ("+ref.compound+")"
    tmpstring2 = '* '+tmpstring2.center(stringlen)+' *\n'
    docstring += tmpstring2
    docstring += '* '+ref.referencestring().center(stringlen)+' *\n'
    docstring += tmpstring
    return docstring

################################################################################################
# Output cell to new CIF file
if outputprogram == 'cif':
    f = open(outputfile,'w')
    cf = CifFile.CifFile()
    cb = CifFile.CifBlock()
    if makesupercell:
        a = cd.latticevectors[0].scalmult(cd.lengthscale)
        b = cd.latticevectors[1].scalmult(cd.lengthscale)
        c = cd.latticevectors[2].scalmult(cd.lengthscale)
	cb['_cell_length_a'] = a.length()
	cb['_cell_length_b'] = b.length()
	cb['_cell_length_c'] = c.length()
	cb['_cell_angle_alpha'] = acos(b.dot(c)/(b.length()*c.length()))*180/pi
	cb['_cell_angle_beta'] = acos(a.dot(c)/(a.length()*c.length()))*180/pi
	cb['_cell_angle_gamma'] = acos(b.dot(a)/(a.length()*b.length()))*180/pi
    # Supercell may have broken symmetry, so just put P1
        cb['_space_group_IT_number'] = 1
        cb['_space_group_name_H-M_alt'] = "P1"
    else:
        # Cell parameters
        cb['_cell_length_a'] = cd.a
        cb['_cell_length_b'] = cd.b
        cb['_cell_length_c'] = cd.c
        cb['_cell_angle_alpha'] = cd.alpha
        cb['_cell_angle_beta']  = cd.beta
        cb['_cell_angle_gamma'] = cd.gamma
        cb['_space_group_IT_number'] = cd.spacegroupnr
        cb['_space_group_name_H-M_alt'] = cd.HMSymbol
        cb['_space_group_name_Hall'] = cd.HallSymbol
    # Positions
    labels = []
    symbols = []
    symmult = []
    fractx = []
    fracty = []
    fractz = []
    occup = []
    for a in cell.atomdata:
        for b in a:
            for k in b.species:
                labels.append(k)
                symbols.append(k)
                symmult.append(str(len(a)))
                fractx.append(str(b.position[0]))
                fracty.append(str(b.position[1]))
                fractz.append(str(b.position[2]))
                occup.append(str(b.species[k]))
    #
    cb.AddCifItem(([['_atom_site_label',
                    '_atom_site_type_symbol',
                    '_atom_site_symmetry_multiplicity',
                    '_atom_site_fract_x',
                    '_atom_site_fract_y',
                    '_atom_site_fract_z',
                    '_atom_site_occupancy']],
                   [[labels,symbols,symmult,fractx,fracty,fractz,occup]]))
    #
    cf['1-cif2cell'] = cb
    f.write(str(cf))
    f.close()

################################################################################################
# Output for Crystal09
if outputprogram == 'crystal09':
    # Get documentation string
    docstring = StandardDocstring()
    # Get output file object
    crystal09file = Crystal09File(cell, docstring)
    crystal09file.spacegroupnr = cd.spacegroupnr
    crystal09file.a = cd.a
    crystal09file.b = cd.b
    crystal09file.c = cd.c
    crystal09file.alpha = cd.alpha
    crystal09file.beta  = cd.beta
    crystal09file.gamma = cd.gamma
    if cd.crystal_system() == "trigonal":
        # Get rhombohedral cell parameters
        if reducetoprim and abs(cd.gamma-120) < cd.coordepsilon:
            a = sqrt(3*cd.a**2 + cd.c**2)/3
            alpha = 360*asin(3/(2*sqrt(3+(cd.c/cd.a)**2)))/pi
            crystal09file.a = a
            crystal09file.b = a
            crystal09file.c = a
            crystal09file.alpha = alpha
            crystal09file.beta = alpha
            crystal09file.gamma = alpha
            crystal09file.trigonalsetting = "R"
    # Print to file
    f = open(outputfile, outmode)
    f.write(str(crystal09file))
    f.close()
    sys.exit(0)

################################################################################################
# Output for Fleur
if outputprogram == 'fleur':
    # The first line with info from the CIF file and species order
    docstring = "Generated by "+programname+" "+version+" : "+ref.cpd+" ("+ref.compound+")"+" :  "+ref.referencestring()
    fleurinput = FleurFile(cell, docstring)
    f = open(outputfile, outmode)
    f.write(str(fleurinput))
    f.close()
    
################################################################################################
# Output for CASTEP
if outputprogram == 'castep':
    docstring = StandardDocstring()
    castepinput = CASTEPFile(cell, docstring)
    f = open(outputfile, outmode)
    f.write(str(castepinput))
    f.close()
    
################################################################################################
# Output for CPMD
if outputprogram == 'cpmd':
    docstring = StandardDocstring()
    cpmdinput = CPMDFile(cell, docstring)
    f = open(outputfile, outmode)
    f.write(str(cpmdinput))
    f.close()
    
################################################################################################
# Output for Siesta
if outputprogram == 'siesta':
    docstring = StandardDocstring()
    siestainput = SiestaFile(cell, docstring)
    f = open(outputfile, outmode)
    f.write(str(siestainput))
    f.close()
    
################################################################################################
# Output for ABINIT
if outputprogram == 'abinit':
    docstring = StandardDocstring()
    abinitinput = ABINITFile(cell, docstring)
    f = open(outputfile, outmode)
    f.write(str(abinitinput))
    f.close()
    
################################################################################################
# Output for VASP
if outputprogram == 'vasp':
    # The first line with info from the CIF file and species order
    docstring =  "Generated by "+programname+" "+version
    if ref.database != "" and ref.databasecode != "":
        docstring += " from "+ref.databaseabbr[ref.database]+" reference: "+ref.databasecode
    docstring += ". "
    if len(ref.cpd) > len(ref.compound):
        docstring += ref.compound
    else:
        docstring += ref.cpd
    docstring += " :  "+ref.referencestring()+"."
    # Initialize the POSCARFile structure
    poscar = POSCARFile(cell, docstring)
    # Convert to cartesian coordinates if requested
    if options.vaspcartpos:
        poscar.printcartpos = True
    if options.vaspcartvecs:
        poscar.printcartvecs = True
    if options.vaspcart:
        poscar.printcartpos = True
        poscar.printcartvecs = True
    if options.vaspformat == "5":
        poscar.vasp5format = True
    f = open(outputfile, outmode)
    f.write(str(poscar))
    f.close()
    # Print species order to screen if requested
    if options.vaspprintspcs:
        print poscar.SpeciesOrder()
    # Set up all files?
    if setupall:
        # POTCAR
        if options.vasppseudolib:
            lib = options.vasppseudolib
        else:
            lib = ""
        potcarfile = POTCARFile(cell,directory=lib)
        f = open("POTCAR", "w")
        f.write(str(potcarfile))
        f.close()
        # KPOINTS
        docstring="Generated by cif2cell "+version+"."
        kpointsfile = KPOINTSFile(cell,docstring=docstring,kresolution=kresolution)
        f = open("KPOINTS", "w")
        f.write(str(kpointsfile))
        f.close()
        # INCAR
        incarfile = INCARFile(cell,docstring=docstring)
        f = open("INCAR", "w")
        f.write(str(incarfile))
        f.close()
    sys.exit(0)
    
################################################################################################
# Output for elk
if outputprogram == 'elk':
    # Get documentation string
    docstring = StandardDocstring()
    # Get output file object
    geometryfile = ElkFile(cell, docstring)
    f = open(outputfile, outmode)
    f.write(str(geometryfile))
    f.close()
    sys.exit(0)

################################################################################################
# Output for exciting
if outputprogram == 'exciting':
    # Get documentation string
    docstring = StandardDocstring()
    # Get output file object
    excitingfile = ExcitingFile(cell, docstring)
    f = open(outputfile, outmode)
    f.write(str(excitingfile))
    f.close()
    sys.exit(0)

################################################################################################
# Output for spacegroup.in for Elk/Exciting cell utility spacegroup
if outputprogram == 'spacegroup':
    # Get documentation string
    docstring = StandardDocstring()
    # Get output file object
    spacegroupfile = SpacegroupFile(cell, docstring)
    angtobohr = 1e-10 * 4 * pi * 10973731.568527/7.2973525376e-3
    spacegroupfile.HermannMauguin = cd.HMSymbol.replace("/","")
    spacegroupfile.a = cd.a*angtobohr
    spacegroupfile.b = cd.b*angtobohr
    spacegroupfile.c = cd.c*angtobohr
    spacegroupfile.alpha = cd.alpha
    spacegroupfile.beta  = cd.beta
    spacegroupfile.gamma = cd.gamma
    if options.spacegroupsupercell:
        spacegroupfile.supercelldims = eval(options.spacegroupsupercell)
    # Print to file
    f = open(outputfile, outmode)
    f.write(str(spacegroupfile))
    f.close()
    sys.exit(0)

################################################################################################
# Output for RSPt
if outputprogram == 'rspt':
    # Construct documentation string
    docstring = StandardDocstring()
    # Get file string and print to symt.inp
    if options.newsymt:
        symtfile = SymtFile2(cell, docstring)
        # spin polarization and relativity
        if options.rsptspinpol:
            symtfile.spinpol = True
        if options.rsptrelativistic:
            symtfile.relativistic = True
        if options.rsptmtradii:
            symtfile.mtradii = int(options.rsptmtradii)
    else:
        symtfile = SymtFile(cell, docstring)
    # spin axis 
    if options.rsptspinaxis:
        symtfile.spinaxis = eval(options.rsptspinaxis)
    f = open(outputfile, outmode)
    f.write(str(symtfile))
    f.close()
    sys.exit(0)
    
################################################################################################
# Output for RSPt supercell generator cellgen
if outputprogram == 'cellgen':
    # Construct documentation string
    docstring = StandardDocstring()
    # Initialize file object
    cellgenfile = CellgenFile(cell, docstring)
    if options.cellgenrefvec:
        cellgenfile.referencevector = eval(options.cellgenrefvec)
    if options.cellgensupercelldims:
        tmplist = eval(options.cellgensupercelldims)
        tmpmat = []
        for i in range(3):
            tmpmat.append([])
            for j in range(3):
                tmpmat[i].append(0)
            tmpmat[i][i] = tmplist[i]
        cellgenfile.supercellmap = tmpmat
    if options.cellgenmap:
        tmpmat = eval(options.cellgenmap)
        cellgenfile.supercellmap = tmpmat
    # Print to file
    f = open(outputfile, outmode)
    f.write(str(cellgenfile))
    f.close()
    sys.exit(0)

################################################################################################
# Output for TB-LMTO program ncol
if outputprogram == 'ncol' or outputprogram == 'bstr':
    # Set up names for files. 
    if cd.spacegroupsymbol == "":
        bstrjobnam = ref.cpd.replace(" ", "").replace("(","").replace(")","")
    else:
        bstrjobnam = cd.spacegroupsymbol.replace("/","")
    jobnam = ref.cpd.replace(" ", "").replace("(","").replace(")","")
    # If the jobnames are long, replace by the name of the cif file
    if len(bstrjobnam) > 30 and len(cif_file_name) < len(bstrjobnam)+4:
        bstrjobnam = cif_file_name.replace(".cif","")
    if len(jobnam) > 10:
        if len(cif_file_name) < len(jobnam):
            jobnam = cif_file_name.replace(".cif","")
        else:
            jobnam = jobnam[0:9]
    # Build docstring
    docstring = ref.compound+", "+ref.referencestring()
    # Document details of creation
    programdoc = "Generated by "+programname+" "+version+" "+datestring
        
# Output for TB-LMTO structure constant program bstr
if outputprogram == 'bstr' or outputprogram == 'ncol':
    # Initialize BSTRFile
    bstrfile = BSTRFile(cell, docstring)
    bstrfile.jobnam = bstrjobnam
    bstrfile.a = cd.a
    bstrfile.b = cd.b
    bstrfile.c = cd.c
    # Document program
    bstrfile.programdoc = programdoc
    f = open(bstrjobnam+".dat","w")
    f.write(str(bstrfile))
    f.close()
    if outputprogram == 'bstr':
        sys.exit(0)

if outputprogram == 'ncol':
    # Initialize ncolfile
    ncolfile = OldNCOLFile(cell, docstring)
    ncolfile.jobnam = jobnam
    ncolfile.bstrjobnam = bstrjobnam
    # Document program
    ncolfile.programdoc = programdoc
    f = open(jobnam+".dat","w")
    f.write(str(ncolfile))
    f.close()
    sys.exit(0)

################################################################################################
# EMTO PROGRAMS
if outputprogram == "emto" or outputprogram == "kgrn" or outputprogram == "kfcd" or outputprogram == "kstr" or outputprogram == "bmdl" or outputprogram == "shape":
    # Get job names
    if cd.spacegroupsymbol == "":
        kstrjobnam = ref.cpd.replace(" ", "").replace("(","").replace(")","")
    else:
        kstrjobnam = cd.spacegroupsymbol.replace("/","")
    kgrnjobnam = ref.cpd.replace(" ", "").replace("(","").replace(")","")
    # If the jobnames are long, replace by the name of the cif file
    if len(kstrjobnam) > 30 and len(cif_file_name) < len(kstrjobnam)+4:
        kstrjobnam = cif_file_name.replace(".cif","")
    if len(kgrnjobnam) > 30 and len(cif_file_name) < len(kgrnjobnam)+4:
        kgrnjobnam = cif_file_name.replace(".cif","")
    # Build docstring
    docstring = ref.compound+", "+ref.referencestring()
    # Document details of creation
    programdoc = "Generated by "+programname+" "+version+" "+datestring
    # Set the lattice number
    if cd.crystal_system() == "cubic":
        if cd.spacegroupsymbol[0] == "F":
            latticenr = 2
        elif cd.spacegroupsymbol[0] == "I":
            latticenr = 3
        else:
            latticenr = 1
    elif cd.crystal_system() == "hexagonal":
        latticenr = 4
    elif cd.crystal_system() == "tetragonal":
        if cd.spacegroupsymbol == "I":
            latticenr = 6
        else:
            latticenr = 5
    elif cd.crystal_system() == "trigonal":
        latticenr = 7
    elif cd.crystal_system() == "orthorhombic":
        if cd.spacegroupsymbol[0] == "A":
            latticenr = 9
        elif cd.spacegroupsymbol[0] == "B":
            latticenr = 9
        elif cd.spacegroupsymbol[0] == "C":
            latticenr = 9
        elif cd.spacegroupsymbol[0] == "I":
            latticenr = 10
        elif cd.spacegroupsymbol[0] == "F":
            latticenr = 11
        else:
            latticenr = 8
    elif cd.crystal_system() == "monoclinic":
        if cd.spacegroupsymbol[0] == "A":
            latticenr = 13
        elif cd.spacegroupsymbol[0] == "B":
            latticenr = 13
        elif cd.spacegroupsymbol[0] == "C":
            latticenr = 13
        else:
            latticenr = 12
    else:
        # Triclinic and default
        latticenr = 14

# Output for EMTO slope matrix program kstr
if outputprogram == 'kstr' or outputprogram == 'emto':
    # Create directories
    try:
        os.mkdir('kstr')
    except OSError:
        pass
    try:
        os.mkdir('kstr/smx')
    except OSError:
        pass
    # Initialize BSTRFile
    kstrfile = KSTRFile(cell, docstring)
    kstrfile.jobnam = kstrjobnam
    if options.hardsphereradii:
        kstrfile.hardsphere = float(options.hardsphereradii)
    kstrfile.latticenr = latticenr
    kstrfile.a = cd.a
    kstrfile.b = cd.b
    kstrfile.c = cd.c
    kstrfile.alpha = cd.alpha
    kstrfile.beta = cd.beta
    kstrfile.gamma = cd.gamma
    # Document program
    kstrfile.programdoc = programdoc
    f = open("kstr/"+kstrjobnam+".dat","w")
    f.write(str(kstrfile))
    f.close()
    if outputprogram == "kstr":
        sys.exit(0)
# Output for EMTO Madelung constant program bmdl
if outputprogram == 'bmdl' or outputprogram == 'emto':
    # Create directories
    try:
        os.mkdir('bmdl')
    except OSError:
        pass
    try:
        os.mkdir('bmdl/mdl')
    except OSError:
        pass
    # Initialize BMDLFile
    bmdlfile = BMDLFile(cell, docstring)
    bmdlfile.jobnam = kstrjobnam
    bmdlfile.latticenr = latticenr
    bmdlfile.a = cd.a
    bmdlfile.b = cd.b
    bmdlfile.c = cd.c
    bmdlfile.alpha = cd.alpha
    bmdlfile.beta = cd.beta
    bmdlfile.gamma = cd.gamma
    # Document program
    bmdlfile.programdoc = programdoc
    f = open("bmdl/"+kstrjobnam+".dat","w")
    f.write(str(bmdlfile))
    f.close()
    if outputprogram == "bmdl":
        sys.exit(0)
# Output for EMTO shape function program 'shape'
if outputprogram == 'shape' or outputprogram == 'emto':
    # Create directories
    try:
        os.mkdir('shape')
    except OSError:
        pass
    try:
        os.mkdir('shape/shp')
    except OSError:
        pass
    # Initialize ShapeFile
    shapefile = ShapeFile(cell, docstring)
    shapefile.jobnam = kstrjobnam
    # Document program
    shapefile.programdoc = programdoc
    f = open("shape/"+kstrjobnam+".dat","w")
    f.write(str(shapefile))
    f.close()
    if outputprogram == "shape":
        sys.exit(0)
# Output for EMTO main Greens function program 'kgrn'
if outputprogram == 'kgrn' or outputprogram == 'emto':
    # Create directories
    try:
        os.mkdir('kgrn')
    except OSError:
        pass
    try:
        os.mkdir('kgrn/pot')
    except OSError:
        pass
    try:
        os.mkdir('kgrn/chd')
    except OSError:
        pass
    # Initialize KGRNFile
    kgrnfile = KGRNFile(cell, docstring)
    kgrnfile.jobnam = kgrnjobnam
    kgrnfile.kstrjobnam = kstrjobnam
    kgrnfile.latticenr = latticenr
    # Document program
    kgrnfile.programdoc = programdoc
    f = open("kgrn/"+kgrnjobnam+".dat","w")
    f.write(str(kgrnfile))
    f.close()
    if outputprogram == "kgrn":
        sys.exit(0)
# Output for EMTO charge density program 'kfcd'
if outputprogram == 'kfcd' or outputprogram == 'emto':
    # Create directories
    try:
        os.mkdir('kfcd')
    except OSError:
        pass
    # Initialize KFCDFile
    kfcdfile = KFCDFile(cell, docstring)
    kfcdfile.jobnam = kgrnjobnam
    kfcdfile.kstrjobnam = kstrjobnam
    # Document program
    kfcdfile.programdoc = programdoc
    f = open("kfcd/"+kgrnjobnam+".dat","w")
    f.write(str(kfcdfile))
    f.close()
    if outputprogram == "kfcd":
        sys.exit(0)        
if outputprogram == "emto":
    sys.exit(0)

################################################################################################
# Output for xband
if outputprogram == 'xband' or outputprogram == 'sprkkr':
    # The first line with info from the CIF file and species order
    docstring =  "Generated by "+programname+" "+version
    if ref.database != "" and ref.databasecode != "":
        docstring += " from "+ref.databaseabbr[ref.database]+" reference: "+ref.databasecode
    docstring += ". "
    if len(ref.cpd) > len(ref.compound):
        docstring += ref.compound
    else:
        docstring += ref.cpd
    docstring += " :  "+ref.referencestring()+"."
    # Initialize the POSCARFile structure
    sysfile = XBandSysFile(cell, docstring)
    sysfile.filename = outputfile
    if options.sprkkrminangmom:
        sysfile.minangmom=int(options.sprkkrminangmom)
    f = open(outputfile, outmode)
    f.write(str(sysfile))
    f.close()
    sys.exit(0)
    
